name = "helix-mcp-server"
main = "src/worker.js"
compatibility_date = "2025-08-08"
compatibility_flags = ["nodejs_compat"]

# Choose your account ID here:
account_id = "852dfa4ae1b0d579df29be65b986c101"

[env.production]
name = "helix-mcp"

[env.staging]
name = "helix-mcp-staging"

[build]
command = "echo 'No build step required'"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
